version: '3.8'

x-volume-root-project: &volume_root_project "./:/var/www/html"

networks:
  docker:
    driver: bridge

services:

  app:
    restart: always
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - *volume_root_project
    networks:
      - docker
    environment:
      PHP_IDE_CONFIG: "serverName=app"

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - "./docker/nginx/conf.d:/etc/nginx/conf.d:ro"
      - *volume_root_project
    networks:
      - docker
    ports:
      - "8098:80"
    depends_on:
      - app


###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - docker
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
