version: '3.8'

x-volume-root-project: &volume_root_project "./:/var/www/html"

networks:
  docker:
    driver: bridge

services:

  app:
    restart: always
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - *volume_root_project
    networks:
      - docker
    depends_on:
      - database

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - "./docker/nginx/conf.d:/etc/nginx/conf.d:ro"
      - *volume_root_project
    networks:
      - docker
    ports:
      - "8098:80"
    depends_on:
      - app
      - database


###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    ports:
      - "55432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - docker
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
